// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea3.Data;

#nullable disable

namespace tarea3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210015626_InitialInventario")]
    partial class InitialInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Tarea3.Models.Producto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Tarea3.Models.Reparacion", b =>
                {
                    b.Property<string>("ID_Reparacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoReparacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dispositivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoServicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FallaReportada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("ID_Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ID_Tecnico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Reparacion");

                    b.ToTable("Reparaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
